{"name": "test_sub[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'\n  +None\n  -'请输入数字'", "trace": "self = <test_pytest.test_calc_new.TestCalc object at 0x7f87b34f5d90>, get_calc = <test_pytest.pythoncode.calculator.Calculator object at 0x7f87b3534910>\nget_subdatas = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=2)\n    def test_sub(self, get_calc, get_subdatas):\n        result = None\n        try:\n            # 调用sub函数,返回的结果保存在result里面\n            result = get_calc.sub(get_subdatas[0], get_subdatas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_subdatas[2]\nE       AssertionError: assert None == '请输入数字'\nE         +None\nE         -'请输入数字'\n\ntest_calc_new.py:50: AssertionError"}, "parameters": [{"name": "get_subdatas", "value": "['', 5, '请输入数字']"}], "start": 1609753927475, "stop": 1609753927475, "uuid": "73f89d54-ad15-4f1c-a632-118327772cf6", "historyId": "b3b1be734d8c94ae56a4d80e99cacfe8", "testCaseId": "a1506a2b3b61cae69056fcb454df3b1b", "fullName": "test_calc_new.TestCalc#test_sub", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MacBook-Pro-2.local"}, {"name": "thread", "value": "43248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}