{"name": "test_div[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'\n  +None\n  -'请输入数字'", "trace": "self = <test_pytest.test_calc_new.TestCalc object at 0x7f87b3548c70>, get_calc = <test_pytest.pythoncode.calculator.Calculator object at 0x7f87b3534910>\nget_divdatas = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_divdatas):\n        result = None\n        try:\n            # 调用div函数,返回的结果保存在result里面\n            result = get_calc.div(get_divdatas[0], get_divdatas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_divdatas[2]\nE       AssertionError: assert None == '请输入数字'\nE         +None\nE         -'请输入数字'\n\ntest_calc_new.py:64: AssertionError"}, "parameters": [{"name": "get_divdatas", "value": "['', 5, '请输入数字']"}], "start": 1609753927743, "stop": 1609753927743, "uuid": "9a230342-8467-4e2d-9da8-a35d60d191e2", "historyId": "7b4b943f9bd11bbcf9b80c1fda32b170", "testCaseId": "609ad21c188e7e060f5fa127da920487", "fullName": "test_calc_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MacBook-Pro-2.local"}, {"name": "thread", "value": "43248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}